=== timocontecht/neighborhoodPSS/pssplugin/src/main/resources/indicatorPlugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/indicatorPlugin/" targetNamespace="http://www.example.org/indicatorPlugin/">
    
    <complexType name="plugin">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="className" type="string"></element>
    		<element name="description" type="string"></element>
    		<element name="author" type="string"></element>
    		<element name="version" type="string"></element>
    		<element name="jar" type="string"></element>
    		<element name="data" type="tns:data" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="data">
    	<sequence>
    		<element name="building-property" type="tns:building-property" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="building-property">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="type" type="string"></element>
    		<element name="max" type="string"></element>
    		<element name="min" type="string"></element>
    		<element name="default" type="string"></element>
    	</sequence>
    </complexType>

    <element name="plugin" type="tns:plugin"></element>
</schema>

=== timocontecht/neighborhoodPSS/NeighborhoodPSS/src/main/webapp/WEB-INF/plugins/deterioation.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:plugin xmlns:tns="http://www.example.org/indicatorPlugin/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/indicatorPlugin/ ../../main/resources/indicatorPlugin.xsd ">
 <name>Test Indicator 1</name>
	<className>org.visico.neighborhoodpss.deterioationindicator.DeterioationIndicator</className>
	<description>Indicator to test dynamic loading</description>
	<author> Timo Hartmann</author>
	<version>1.0</version>
	<jar>deterioationindicator-0.0.1-SNAPSHOT.jar</jar>
	
	<data>
		<building-property>
				<name>Condition</name>
				<type>Integer</type>
				<max>5</max>
				<min>0</min>
				<default>3</default>
		</building-property>
	</data>
</tns:plugin>
